///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AnnouncementModelDataAnnouncementLanguage {
/*
{
  "id": 15,
  "announcement_id": 8,
  "language_id": 1,
  "name": "The company president made an announcement about the merger. He asked us to pay attention because he had an important announcement to make",
  "status": 1,
  "created_at": "06:37:30 am",
  "updated_at": "2024-06-04T10:02:46.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  int? announcementId;
  int? languageId;
  String? name;
  int? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  AnnouncementModelDataAnnouncementLanguage({
    this.id,
    this.announcementId,
    this.languageId,
    this.name,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  AnnouncementModelDataAnnouncementLanguage.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    announcementId = json['announcement_id']?.toInt();
    languageId = json['language_id']?.toInt();
    name = json['name']?.toString();
    status = json['status']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['announcement_id'] = announcementId;
    data['language_id'] = languageId;
    data['name'] = name;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class AnnouncementModelData {
/*
{
  "id": 8,
  "name": "The company president made an announcement about the merger. He asked us to pay attention because he had an important announcement to make",
  "date": "2024-05-18",
  "status": true,
  "created_at": "2024-05-17T06:37:30.000000Z",
  "updated_at": "2024-06-04T10:02:46.000000Z",
  "deleted_at": null,
  "announcement_language": {
    "id": 15,
    "announcement_id": 8,
    "language_id": 1,
    "name": "The company president made an announcement about the merger. He asked us to pay attention because he had an important announcement to make",
    "status": 1,
    "created_at": "06:37:30 am",
    "updated_at": "2024-06-04T10:02:46.000000Z",
    "deleted_at": null
  }
} 
*/

  int? id;
  String? name;
  String? date;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  AnnouncementModelDataAnnouncementLanguage? announcementLanguage;

  AnnouncementModelData({
    this.id,
    this.name,
    this.date,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.announcementLanguage,
  });
  AnnouncementModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    date = json['date']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    announcementLanguage = (json['announcement_language'] != null) ? AnnouncementModelDataAnnouncementLanguage.fromJson(json['announcement_language']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['date'] = date;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    if (announcementLanguage != null) {
      data['announcement_language'] = announcementLanguage!.toJson();
    }
    return data;
  }
}

class AnnouncementModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 8,
      "name": "The company president made an announcement about the merger. He asked us to pay attention because he had an important announcement to make",
      "date": "2024-05-18",
      "status": true,
      "created_at": "2024-05-17T06:37:30.000000Z",
      "updated_at": "2024-06-04T10:02:46.000000Z",
      "deleted_at": null,
      "announcement_language": {
        "id": 15,
        "announcement_id": 8,
        "language_id": 1,
        "name": "The company president made an announcement about the merger. He asked us to pay attention because he had an important announcement to make",
        "status": 1,
        "created_at": "06:37:30 am",
        "updated_at": "2024-06-04T10:02:46.000000Z",
        "deleted_at": null
      }
    }
  ],
  "message": "announcement Get successfully."
} 
*/

  bool? success;
  List<AnnouncementModelData?>? data;
  String? message;

  AnnouncementModel({
    this.success,
    this.data,
    this.message,
  });
  AnnouncementModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <AnnouncementModelData>[];
  v.forEach((v) {
  arr0.add(AnnouncementModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
