///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyHistoryModelDataLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
} 
*/

  String? url;
  String? label;
  bool? active;

  MyHistoryModelDataLinks({
    this.url,
    this.label,
    this.active,
  });
  MyHistoryModelDataLinks.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    label = json['label']?.toString();
    active = json['active'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['label'] = label;
    data['active'] = active;
    return data;
  }
}

class MyHistoryModelDataData {
/*
{
  "id": 565,
  "period": "8037",
  "color": "Green",
  "number": null,
  "size": null,
  "result": "Failed",
  "profit": "0.00",
  "loss": "0.00",
  "created_at": "2024-05-29T11:49:35.000000Z"
} 
*/

  int? id;
  String? period;
  String? color;
  String? number;
  String? size;
  String? result;
  String? profit;
  String? loss;
  String? createdAt;

  MyHistoryModelDataData({
    this.id,
    this.period,
    this.color,
    this.number,
    this.size,
    this.result,
    this.profit,
    this.loss,
    this.createdAt,
  });
  MyHistoryModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    period = json['period']?.toString();
    color = json['color']?.toString();
    number = json['number']?.toString();
    size = json['size']?.toString();
    result = json['result']?.toString();
    profit = json['profit']?.toString();
    loss = json['loss']?.toString();
    createdAt = json['created_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['period'] = period;
    data['color'] = color;
    data['number'] = number;
    data['size'] = size;
    data['result'] = result;
    data['profit'] = profit;
    data['loss'] = loss;
    data['created_at'] = createdAt;
    return data;
  }
}

class MyHistoryModelData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 565,
      "period": "8037",
      "color": "Green",
      "number": null,
      "size": null,
      "result": "Failed",
      "profit": "0.00",
      "loss": "0.00",
      "created_at": "2024-05-29T11:49:35.000000Z"
    }
  ],
  "first_page_url": "https://omwinner.profcymabackend.com/public/api/myHistory?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "https://omwinner.profcymabackend.com/public/api/myHistory?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "https://omwinner.profcymabackend.com/public/api/myHistory",
  "per_page": 10,
  "prev_page_url": null,
  "to": 3,
  "total": 3
} 
*/

  int? currentPage;
  List<MyHistoryModelDataData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<MyHistoryModelDataLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  MyHistoryModelData({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  MyHistoryModelData.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MyHistoryModelDataData>[];
      v.forEach((v) {
        arr0.add(MyHistoryModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json['first_page_url']?.toString();
    from = json['from']?.toInt();
    lastPage = json['last_page']?.toInt();
    lastPageUrl = json['last_page_url']?.toString();
    if (json['links'] != null) {
      final v = json['links'];
      final arr0 = <MyHistoryModelDataLinks>[];
      v.forEach((v) {
        arr0.add(MyHistoryModelDataLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json['next_page_url']?.toString();
    path = json['path']?.toString();
    perPage = json['per_page']?.toInt();
    prevPageUrl = json['prev_page_url']?.toString();
    to = json['to']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['first_page_url'] = firstPageUrl;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['last_page_url'] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['links'] = arr0;
    }
    data['next_page_url'] = nextPageUrl;
    data['path'] = path;
    data['per_page'] = perPage;
    data['prev_page_url'] = prevPageUrl;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class MyHistoryModel {
/*
{
  "success": true,
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 565,
        "period": "8037",
        "color": "Green",
        "number": null,
        "size": null,
        "result": "Failed",
        "profit": "0.00",
        "loss": "0.00",
        "created_at": "2024-05-29T11:49:35.000000Z"
      }
    ],
    "first_page_url": "https://omwinner.profcymabackend.com/public/api/myHistory?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "https://omwinner.profcymabackend.com/public/api/myHistory?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "https://omwinner.profcymabackend.com/public/api/myHistory",
    "per_page": 10,
    "prev_page_url": null,
    "to": 3,
    "total": 3
  },
  "message": "My History Get successfully."
} 
*/

  bool? success;
  MyHistoryModelData? data;
  String? message;

  MyHistoryModel({
    this.success,
    this.data,
    this.message,
  });
  MyHistoryModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? MyHistoryModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
