///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WalletBalanceModelData {
/*
{
  "total_deposit": "10000.00",
  "total_withdraw": "300.00",
  "available_balance": "9700.00"
} 
*/

  String? totalDeposit;
  String? totalWithdraw;
  String? availableBalance;

  WalletBalanceModelData({
    this.totalDeposit,
    this.totalWithdraw,
    this.availableBalance,
  });
  WalletBalanceModelData.fromJson(Map<String, dynamic> json) {
    totalDeposit = json['total_deposit']?.toString();
    totalWithdraw = json['total_withdraw']?.toString();
    availableBalance = json['available_balance']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total_deposit'] = totalDeposit;
    data['total_withdraw'] = totalWithdraw;
    data['available_balance'] = availableBalance;
    return data;
  }
}

class WalletBalanceModel {
/*
{
  "success": true,
  "data": {
    "total_deposit": "10000.00",
    "total_withdraw": "300.00",
    "available_balance": "9700.00"
  },
  "message": "Balance Get successfully."
} 
*/

  bool? success;
  WalletBalanceModelData? data;
  String? message;

  WalletBalanceModel({
    this.success,
    this.data,
    this.message,
  });
  WalletBalanceModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? WalletBalanceModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
