///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WithdrawPostModelData {
/*
{
  "user_id": 5,
  "wallet_id": 1,
  "transaction_type": "UPI",
  "transaction_number": "upi4563217890",
  "amount": "300",
  "type": "Withdraw",
  "mobile_number": "9975279494",
  "name": "Saurabh",
  "status": true,
  "updated_at": "2024-05-02T11:48:23.000000Z",
  "created_at": "2024-05-02T11:48:23.000000Z",
  "id": 3
} 
*/

  int? userId;
  int? walletId;
  String? transactionType;
  String? transactionNumber;
  String? amount;
  String? type;
  String? mobileNumber;
  String? name;
  bool? status;
  String? updatedAt;
  String? createdAt;
  int? id;

  WithdrawPostModelData({
    this.userId,
    this.walletId,
    this.transactionType,
    this.transactionNumber,
    this.amount,
    this.type,
    this.mobileNumber,
    this.name,
    this.status,
    this.updatedAt,
    this.createdAt,
    this.id,
  });
  WithdrawPostModelData.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toInt();
    walletId = json['wallet_id']?.toInt();
    transactionType = json['transaction_type']?.toString();
    transactionNumber = json['transaction_number']?.toString();
    amount = json['amount']?.toString();
    type = json['type']?.toString();
    mobileNumber = json['mobile_number']?.toString();
    name = json['name']?.toString();
    status = json['status'];
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['wallet_id'] = walletId;
    data['transaction_type'] = transactionType;
    data['transaction_number'] = transactionNumber;
    data['amount'] = amount;
    data['type'] = type;
    data['mobile_number'] = mobileNumber;
    data['name'] = name;
    data['status'] = status;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    return data;
  }
}

class WithdrawPostModel {
/*
{
  "success": true,
  "data": {
    "user_id": 5,
    "wallet_id": 1,
    "transaction_type": "UPI",
    "transaction_number": "upi4563217890",
    "amount": "300",
    "type": "Withdraw",
    "mobile_number": "9975279494",
    "name": "Saurabh",
    "status": true,
    "updated_at": "2024-05-02T11:48:23.000000Z",
    "created_at": "2024-05-02T11:48:23.000000Z",
    "id": 3
  },
  "message": "Withdraw added successfully."
} 
*/

  bool? success;
  WithdrawPostModelData? data;
  String? message;

  WithdrawPostModel({
    this.success,
    this.data,
    this.message,
  });
  WithdrawPostModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? WithdrawPostModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
