///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpcommingGameModelData {
/*
{
  "id": 1,
  "name": "LUDO",
  "image": "public/admin/home/40blue-and-red-thor-stormbreaker-outline-0g6ulj4o11mfr070.jpg",
  "status": true,
  "created_at": "2024-04-30T09:39:39.000000Z",
  "updated_at": "2024-04-30T09:40:34.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  String? name;
  String? image;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  UpcommingGameModelData({
    this.id,
    this.name,
    this.image,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  UpcommingGameModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class UpcommingGameModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "name": "LUDO",
      "image": "public/admin/home/40blue-and-red-thor-stormbreaker-outline-0g6ulj4o11mfr070.jpg",
      "status": true,
      "created_at": "2024-04-30T09:39:39.000000Z",
      "updated_at": "2024-04-30T09:40:34.000000Z",
      "deleted_at": null
    }
  ],
  "message": "Upcomming Games Get successfully."
} 
*/

  bool? success;
  List<UpcommingGameModelData?>? data;
  String? message;

  UpcommingGameModel({
    this.success,
    this.data,
    this.message,
  });
  UpcommingGameModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <UpcommingGameModelData>[];
  v.forEach((v) {
  arr0.add(UpcommingGameModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
