///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class YesterdayCommissionModelData {
/*
{
  "commission": "0.00"
} 
*/

  String? commission;

  YesterdayCommissionModelData({
    this.commission,
  });
  YesterdayCommissionModelData.fromJson(Map<String, dynamic> json) {
    commission = json['commission']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['commission'] = commission;
    return data;
  }
}

class YesterdayCommissionModel {
/*
{
  "success": true,
  "data": {
    "commission": "0.00"
  },
  "message": "yesterdays commission Get successfully."
} 
*/

  bool? success;
  YesterdayCommissionModelData? data;
  String? message;

  YesterdayCommissionModel({
    this.success,
    this.data,
    this.message,
  });
  YesterdayCommissionModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? YesterdayCommissionModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
