///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AboutUsBannerModelData {
/*
{
  "id": 1,
  "name": "firstt",
  "image": "public/admin/aboutBanner/82LOGO (1).jpg",
  "status": true,
  "created_at": "2024-04-30T11:06:05.000000Z",
  "updated_at": "2024-04-30T11:06:48.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  String? name;
  String? image;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  AboutUsBannerModelData({
    this.id,
    this.name,
    this.image,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  AboutUsBannerModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class AboutUsBannerModel {
/*
{
  "success": true,
  "data": {
    "id": 1,
    "name": "firstt",
    "image": "public/admin/aboutBanner/82LOGO (1).jpg",
    "status": true,
    "created_at": "2024-04-30T11:06:05.000000Z",
    "updated_at": "2024-04-30T11:06:48.000000Z",
    "deleted_at": null
  },
  "message": "About Banner Get successfully."
} 
*/

  bool? success;
  AboutUsBannerModelData? data;
  String? message;

  AboutUsBannerModel({
    this.success,
    this.data,
    this.message,
  });
  AboutUsBannerModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? AboutUsBannerModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
