///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RegisterModelData {
/*
{
  "user": 6,
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODQxN2JmZTMwYWFkM2IzMGMxMDIwYzFhYTI5ODI3ZTYwYWUyZjkwNjNlMWFmNTc3NTVlNmI0ODI3NTBjMzQwYTI2Y2FjYjVmZDY3NDZlNzgiLCJpYXQiOjE3MTUzMTcwNTkuODUzMzEyMDE1NTMzNDQ3MjY1NjI1LCJuYmYiOjE3MTUzMTcwNTkuODUzMzEyOTY5MjA3NzYzNjcxODc1LCJleHAiOjE3NDY4NTMwNTkuODQ1NTQxMDAwMzY2MjEwOTM3NSwic3ViIjoiNiIsInNjb3BlcyI6W119.bRDsiP6cJfHNHdX0SKXvXrr__k_sxiQOiyZXuSbQqCCN8nNO8XhkaswjXsJ1fP9OuP6xhHit37AOA8WzcAV716ssrMlQNah0159QCsSftdrZYOKTxyV4JikHvKEajDy1DQ0vHFicVYSlQ2r28vPvmBYqLuSZdOAeAfuKSnwQHtkJgP4ztIEt2rzo07OIX3vsVPbCKK4bzpQ1ve3MtFeLR3l2AliJk9i27jGi3ll8y1R2O2wx63RDQ5dLt9z8UxB7NQFYlYj2fb9n-1vqEj6YbaUm7_S2Wl-jtOzRxBS8zHSWQ1y7WIM2GygQG7rZPQ0_x4IswRtuXYudmNwpyvOf2AARokLwOPrJveFjXvIkvp0LEu8xcs7iURXWdXj6h-30EA3z-6tkgNGOQQPlj6wYkBB2DvofFdg7LfQ8nYX1UhaeWjgCJBoZT5nboyqsVUriy9GsnfvefpHERxQeQ4vJcglqYDV_rpLNIihgdfqd2QVFd9Lcf8rB4Q8lXzo2c0ma9tV0Fvd_eYbfV3d69QnpBJxvMkqcZGYR6iDddCGGQpTg_CQ0WaZxL1VECL76h6zAgGjRg7mCOPa9Pm1LiLN8i53Irlg0CMBo8X1FNrXUoon7lr48EzdIB6W_wStf9gVtv4CRemOeqfXyXrsW1OBCbH3SY7i3rKumanA8BvxedAc",
  "noti": true
} 
*/

  int? user;
  String? token;
  bool? noti;

  RegisterModelData({
    this.user,
    this.token,
    this.noti,
  });
  RegisterModelData.fromJson(Map<String, dynamic> json) {
    user = json['user']?.toInt();
    token = json['token']?.toString();
    noti = json['noti'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user'] = user;
    data['token'] = token;
    data['noti'] = noti;
    return data;
  }
}

class RegisterModel {
/*
{
  "success": true,
  "data": {
    "user": 6,
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiODQxN2JmZTMwYWFkM2IzMGMxMDIwYzFhYTI5ODI3ZTYwYWUyZjkwNjNlMWFmNTc3NTVlNmI0ODI3NTBjMzQwYTI2Y2FjYjVmZDY3NDZlNzgiLCJpYXQiOjE3MTUzMTcwNTkuODUzMzEyMDE1NTMzNDQ3MjY1NjI1LCJuYmYiOjE3MTUzMTcwNTkuODUzMzEyOTY5MjA3NzYzNjcxODc1LCJleHAiOjE3NDY4NTMwNTkuODQ1NTQxMDAwMzY2MjEwOTM3NSwic3ViIjoiNiIsInNjb3BlcyI6W119.bRDsiP6cJfHNHdX0SKXvXrr__k_sxiQOiyZXuSbQqCCN8nNO8XhkaswjXsJ1fP9OuP6xhHit37AOA8WzcAV716ssrMlQNah0159QCsSftdrZYOKTxyV4JikHvKEajDy1DQ0vHFicVYSlQ2r28vPvmBYqLuSZdOAeAfuKSnwQHtkJgP4ztIEt2rzo07OIX3vsVPbCKK4bzpQ1ve3MtFeLR3l2AliJk9i27jGi3ll8y1R2O2wx63RDQ5dLt9z8UxB7NQFYlYj2fb9n-1vqEj6YbaUm7_S2Wl-jtOzRxBS8zHSWQ1y7WIM2GygQG7rZPQ0_x4IswRtuXYudmNwpyvOf2AARokLwOPrJveFjXvIkvp0LEu8xcs7iURXWdXj6h-30EA3z-6tkgNGOQQPlj6wYkBB2DvofFdg7LfQ8nYX1UhaeWjgCJBoZT5nboyqsVUriy9GsnfvefpHERxQeQ4vJcglqYDV_rpLNIihgdfqd2QVFd9Lcf8rB4Q8lXzo2c0ma9tV0Fvd_eYbfV3d69QnpBJxvMkqcZGYR6iDddCGGQpTg_CQ0WaZxL1VECL76h6zAgGjRg7mCOPa9Pm1LiLN8i53Irlg0CMBo8X1FNrXUoon7lr48EzdIB6W_wStf9gVtv4CRemOeqfXyXrsW1OBCbH3SY7i3rKumanA8BvxedAc",
    "noti": true
  },
  "message": "Register successfully."
} 
*/

  bool? success;
  RegisterModelData? data;
  String? message;

  RegisterModel({
    this.success,
    this.data,
    this.message,
  });
  RegisterModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? RegisterModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
