///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HowToPlayModelDataHowToPlayLanguage {
/*
{
  "id": 3,
  "how_to_play_id": 3,
  "language_id": 1,
  "name": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus must. with Love.",
  "status": 1,
  "created_at": "06:51:27 am",
  "updated_at": "2024-05-17T05:21:08.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  int? howToPlayId;
  int? languageId;
  String? name;
  int? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  HowToPlayModelDataHowToPlayLanguage({
    this.id,
    this.howToPlayId,
    this.languageId,
    this.name,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  HowToPlayModelDataHowToPlayLanguage.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    howToPlayId = json['how_to_play_id']?.toInt();
    languageId = json['language_id']?.toInt();
    name = json['name']?.toString();
    status = json['status']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['how_to_play_id'] = howToPlayId;
    data['language_id'] = languageId;
    data['name'] = name;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class HowToPlayModelData {
/*
{
  "id": 3,
  "name": "Two",
  "status": true,
  "created_at": "2024-05-07T06:51:27.000000Z",
  "updated_at": "2024-05-17T05:21:08.000000Z",
  "deleted_at": null,
  "how_to_play_language": {
    "id": 3,
    "how_to_play_id": 3,
    "language_id": 1,
    "name": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus must. with Love.",
    "status": 1,
    "created_at": "06:51:27 am",
    "updated_at": "2024-05-17T05:21:08.000000Z",
    "deleted_at": null
  }
} 
*/

  int? id;
  String? name;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  HowToPlayModelDataHowToPlayLanguage? howToPlayLanguage;

  HowToPlayModelData({
    this.id,
    this.name,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.howToPlayLanguage,
  });
  HowToPlayModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    howToPlayLanguage = (json['how_to_play_language'] != null)
        ? HowToPlayModelDataHowToPlayLanguage.fromJson(
            json['how_to_play_language'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    if (howToPlayLanguage != null) {
      data['how_to_play_language'] = howToPlayLanguage!.toJson();
    }
    return data;
  }
}

class HowToPlayModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 3,
      "name": "Two",
      "status": true,
      "created_at": "2024-05-07T06:51:27.000000Z",
      "updated_at": "2024-05-17T05:21:08.000000Z",
      "deleted_at": null,
      "how_to_play_language": {
        "id": 3,
        "how_to_play_id": 3,
        "language_id": 1,
        "name": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus must. with Love.",
        "status": 1,
        "created_at": "06:51:27 am",
        "updated_at": "2024-05-17T05:21:08.000000Z",
        "deleted_at": null
      }
    }
  ],
  "message": "How To Play Get successfully."
} 
*/

  bool? success;
  List<HowToPlayModelData?>? data;
  String? message;

  HowToPlayModel({
    this.success,
    this.data,
    this.message,
  });
  HowToPlayModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <HowToPlayModelData>[];
      v.forEach((v) {
        arr0.add(HowToPlayModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
