///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyGameHistoryModelData {
/*
{
  "id": 942,
  "user_id": 137,
  "bet_id": 1617,
  "period": "2135",
  "color": "Red",
  "number": null,
  "size": null,
  "balance": "2",
  "result": "Succeed",
  "amount": "1.00",
  "profit": "2.00",
  "loss": null,
  "commission": "0.00",
  "status": true,
  "created_at": "2024-06-07T06:53:31.000000Z",
  "updated_at": "2024-06-07T06:57:52.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  int? userId;
  int? betId;
  String? period;
  String? color;
  String? number;
  String? size;
  String? balance;
  String? result;
  String? amount;
  String? profit;
  String? loss;
  String? commission;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  MyGameHistoryModelData({
    this.id,
    this.userId,
    this.betId,
    this.period,
    this.color,
    this.number,
    this.size,
    this.balance,
    this.result,
    this.amount,
    this.profit,
    this.loss,
    this.commission,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  MyGameHistoryModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['user_id']?.toInt();
    betId = json['bet_id']?.toInt();
    period = json['period']?.toString();
    color = json['color']?.toString();
    number = json['number']?.toString();
    size = json['size']?.toString();
    balance = json['balance']?.toString();
    result = json['result']?.toString();
    amount = json['amount']?.toString();
    profit = json['profit']?.toString();
    loss = json['loss']?.toString();
    commission = json['commission']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['bet_id'] = betId;
    data['period'] = period;
    data['color'] = color;
    data['number'] = number;
    data['size'] = size;
    data['balance'] = balance;
    data['result'] = result;
    data['amount'] = amount;
    data['profit'] = profit;
    data['loss'] = loss;
    data['commission'] = commission;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class MyGameHistoryModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 942,
      "user_id": 137,
      "bet_id": 1617,
      "period": "2135",
      "color": "Red",
      "number": null,
      "size": null,
      "balance": "2",
      "result": "Succeed",
      "amount": "1.00",
      "profit": "2.00",
      "loss": null,
      "commission": "0.00",
      "status": true,
      "created_at": "2024-06-07T06:53:31.000000Z",
      "updated_at": "2024-06-07T06:57:52.000000Z",
      "deleted_at": null
    }
  ],
  "message": "My History  Get successfully."
} 
*/

  bool? success;
  List<MyGameHistoryModelData?>? data;
  String? message;

  MyGameHistoryModel({
    this.success,
    this.data,
    this.message,
  });
  MyGameHistoryModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MyGameHistoryModelData>[];
      v.forEach((v) {
        arr0.add(MyGameHistoryModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
