///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LatestBetModelData {
/*
{
  "id": 1580,
  "period": "4157",
  "color": null,
  "number": null,
  "size": null,
  "total_amount": "0.00",
  "remaining_amount": "0.00",
  "commission": "0.00",
  "status": true,
  "created_at": "2024-06-06T09:38:43.000000Z",
  "updated_at": "2024-06-06T09:38:43.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  String? period;
  String? color;
  String? number;
  String? size;
  String? totalAmount;
  String? remainingAmount;
  String? commission;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  LatestBetModelData({
    this.id,
    this.period,
    this.color,
    this.number,
    this.size,
    this.totalAmount,
    this.remainingAmount,
    this.commission,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  LatestBetModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    period = json['period']?.toString();
    color = json['color']?.toString();
    number = json['number']?.toString();
    size = json['size']?.toString();
    totalAmount = json['total_amount']?.toString();
    remainingAmount = json['remaining_amount']?.toString();
    commission = json['commission']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['period'] = period;
    data['color'] = color;
    data['number'] = number;
    data['size'] = size;
    data['total_amount'] = totalAmount;
    data['remaining_amount'] = remainingAmount;
    data['commission'] = commission;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class LatestBetModel {
/*
{
  "success": true,
  "data": {
    "id": 1580,
    "period": "4157",
    "color": null,
    "number": null,
    "size": null,
    "total_amount": "0.00",
    "remaining_amount": "0.00",
    "commission": "0.00",
    "status": true,
    "created_at": "2024-06-06T09:38:43.000000Z",
    "updated_at": "2024-06-06T09:38:43.000000Z",
    "deleted_at": null
  },
  "message": "Latest Bet Get successfully."
} 
*/

  bool? success;
  LatestBetModelData? data;
  String? message;

  LatestBetModel({
    this.success,
    this.data,
    this.message,
  });
  LatestBetModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? LatestBetModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
