///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubcordinateModelDataDepositeAmount {
/*
{
  "id": 1,
  "amount": "200",
  "status": true,
  "created_at": "2024-05-27T07:04:43.000000Z",
  "updated_at": "2024-05-27T12:54:18.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  String? amount;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  SubcordinateModelDataDepositeAmount({
    this.id,
    this.amount,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  SubcordinateModelDataDepositeAmount.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    amount = json['amount']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['amount'] = amount;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class SubcordinateModelData {
/*
{
  "total_no_of_bet": 0,
  "total_no_of_betters": 0,
  "total_no_of_deposite": 0,
  "deposite_number": [
    null
  ],
  "deposite_number_total": 0,
  "deposite_amount": {
    "id": 1,
    "amount": "200",
    "status": true,
    "created_at": "2024-05-27T07:04:43.000000Z",
    "updated_at": "2024-05-27T12:54:18.000000Z",
    "deleted_at": null
  }
} 
*/

  int? totalNoOfBet;
  int? totalNoOfBetters;
  int? totalNoOfDeposite;
  List? depositeNumber;
  int? depositeNumberTotal;
  SubcordinateModelDataDepositeAmount? depositeAmount;

  SubcordinateModelData({
    this.totalNoOfBet,
    this.totalNoOfBetters,
    this.totalNoOfDeposite,
    this.depositeNumber,
    this.depositeNumberTotal,
    this.depositeAmount,
  });
  SubcordinateModelData.fromJson(Map<String, dynamic> json) {
    totalNoOfBet = json['total_no_of_bet']?.toInt();
    totalNoOfBetters = json['total_no_of_betters']?.toInt();
    totalNoOfDeposite = json['total_no_of_deposite']?.toInt();

    depositeNumberTotal = json['deposite_number_total']?.toInt();
    depositeAmount = (json['deposite_amount'] != null)
        ? SubcordinateModelDataDepositeAmount.fromJson(json['deposite_amount'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total_no_of_bet'] = totalNoOfBet;
    data['total_no_of_betters'] = totalNoOfBetters;
    data['total_no_of_deposite'] = totalNoOfDeposite;

    data['deposite_number_total'] = depositeNumberTotal;
    if (depositeAmount != null) {
      data['deposite_amount'] = depositeAmount!.toJson();
    }
    return data;
  }
}

class SubcordinateModel {
/*
{
  "success": true,
  "data": {
    "total_no_of_bet": 0,
    "total_no_of_betters": 0,
    "total_no_of_deposite": 0,
    "deposite_number": [
      null
    ],
    "deposite_number_total": 0,
    "deposite_amount": {
      "id": 1,
      "amount": "200",
      "status": true,
      "created_at": "2024-05-27T07:04:43.000000Z",
      "updated_at": "2024-05-27T12:54:18.000000Z",
      "deleted_at": null
    }
  },
  "message": "subordinate Data Get successfully."
} 
*/

  bool? success;
  SubcordinateModelData? data;
  String? message;

  SubcordinateModel({
    this.success,
    this.data,
    this.message,
  });
  SubcordinateModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? SubcordinateModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
