///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotificationDeleteModel {
/*
{
  "success": true,
  "data": 1,
  "message": "Notification Delete successfully."
} 
*/

  bool? success;
  int? data;
  String? message;

  NotificationDeleteModel({
    this.success,
    this.data,
    this.message,
  });
  NotificationDeleteModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = json['data']?.toInt();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['data'] = this.data;
    data['message'] = message;
    return data;
  }
}
