///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InvitationRuleModelDataInvitationRuleLanguage {
/*
{
  "id": 9,
  "invitation_rule_id": 1,
  "language_id": 1,
  "name": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus must. with Love",
  "status": 1,
  "created_at": "08:32:29 am",
  "updated_at": "2024-05-07T08:32:29.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  int? invitationRuleId;
  int? languageId;
  String? name;
  int? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  InvitationRuleModelDataInvitationRuleLanguage({
    this.id,
    this.invitationRuleId,
    this.languageId,
    this.name,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  InvitationRuleModelDataInvitationRuleLanguage.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    invitationRuleId = json['invitation_rule_id']?.toInt();
    languageId = json['language_id']?.toInt();
    name = json['name']?.toString();
    status = json['status']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['invitation_rule_id'] = invitationRuleId;
    data['language_id'] = languageId;
    data['name'] = name;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class InvitationRuleModelData {
/*
{
  "id": 1,
  "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  "status": true,
  "created_at": "2024-04-30T12:08:44.000000Z",
  "updated_at": "2024-05-07T08:32:29.000000Z",
  "deleted_at": null,
  "invitation_rule_language": {
    "id": 9,
    "invitation_rule_id": 1,
    "language_id": 1,
    "name": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus must. with Love",
    "status": 1,
    "created_at": "08:32:29 am",
    "updated_at": "2024-05-07T08:32:29.000000Z",
    "deleted_at": null
  }
} 
*/

  int? id;
  String? description;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  InvitationRuleModelDataInvitationRuleLanguage? invitationRuleLanguage;

  InvitationRuleModelData({
    this.id,
    this.description,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.invitationRuleLanguage,
  });
  InvitationRuleModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    description = json['description']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    invitationRuleLanguage = (json['invitation_rule_language'] != null) ? InvitationRuleModelDataInvitationRuleLanguage.fromJson(json['invitation_rule_language']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['description'] = description;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    if (invitationRuleLanguage != null) {
      data['invitation_rule_language'] = invitationRuleLanguage!.toJson();
    }
    return data;
  }
}

class InvitationRuleModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
      "status": true,
      "created_at": "2024-04-30T12:08:44.000000Z",
      "updated_at": "2024-05-07T08:32:29.000000Z",
      "deleted_at": null,
      "invitation_rule_language": {
        "id": 9,
        "invitation_rule_id": 1,
        "language_id": 1,
        "name": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus must. with Love",
        "status": 1,
        "created_at": "08:32:29 am",
        "updated_at": "2024-05-07T08:32:29.000000Z",
        "deleted_at": null
      }
    }
  ],
  "message": "invitation Rule Get successfully."
} 
*/

  bool? success;
  List<InvitationRuleModelData?>? data;
  String? message;

  InvitationRuleModel({
    this.success,
    this.data,
    this.message,
  });
  InvitationRuleModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <InvitationRuleModelData>[];
  v.forEach((v) {
  arr0.add(InvitationRuleModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
