///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FeedBackModelData {
/*
{
  "user_id": 38,
  "feedback": "hello all thank for feebback",
  "status": true,
  "updated_at": "2024-05-27T07:31:43.000000Z",
  "created_at": "2024-05-27T07:31:43.000000Z",
  "id": 3
} 
*/

  int? userId;
  String? feedback;
  bool? status;
  String? updatedAt;
  String? createdAt;
  int? id;

  FeedBackModelData({
    this.userId,
    this.feedback,
    this.status,
    this.updatedAt,
    this.createdAt,
    this.id,
  });
  FeedBackModelData.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toInt();
    feedback = json['feedback']?.toString();
    status = json['status'];
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['feedback'] = feedback;
    data['status'] = status;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    return data;
  }
}

class FeedBackModel {
/*
{
  "success": true,
  "data": {
    "user_id": 38,
    "feedback": "hello all thank for feebback",
    "status": true,
    "updated_at": "2024-05-27T07:31:43.000000Z",
    "created_at": "2024-05-27T07:31:43.000000Z",
    "id": 3
  },
  "message": "feedback added successfully."
} 
*/

  bool? success;
  FeedBackModelData? data;
  String? message;

  FeedBackModel({
    this.success,
    this.data,
    this.message,
  });
  FeedBackModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? FeedBackModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
