///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotificationModelData {
/*
{
  "id": 1,
  "name": "Your Account is Logged in",
  "date": "2024-05-03",
  "time": "11:00 AM"
} 
*/

  int? id;
  String? name;
  String? date;
  String? time;

  NotificationModelData({
    this.id,
    this.name,
    this.date,
    this.time,
  });
  NotificationModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['date'] = date;
    data['time'] = time;
    return data;
  }
}

class NotificationModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "name": "Your Account is Logged in",
      "date": "2024-05-03",
      "time": "11:00 AM"
    }
  ],
  "message": "Notification Get successfully."
} 
*/

  bool? success;
  List<NotificationModelData?>? data;
  String? message;

  NotificationModel({
    this.success,
    this.data,
    this.message,
  });
  NotificationModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <NotificationModelData>[];
      v.forEach((v) {
        arr0.add(NotificationModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
