///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EditProfileModelData {
/*
{
  "id": 37,
  "name": "khjkj",
  "udi": "25497610",
  "email": null,
  "mobile_number": "9673423411",
  "phone_number": null,
  "device_key": null,
  "image": "admin/home/profile/4386Group 34169.png",
  "type": "customer",
  "email_verified_at": null,
  "status": true,
  "created_at": "2024-05-24T05:12:28.000000Z",
  "updated_at": "2024-05-24T05:33:54.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  String? name;
  String? udi;
  String? email;
  String? mobileNumber;
  String? phoneNumber;
  String? deviceKey;
  String? image;
  String? type;
  String? emailVerifiedAt;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  EditProfileModelData({
    this.id,
    this.name,
    this.udi,
    this.email,
    this.mobileNumber,
    this.phoneNumber,
    this.deviceKey,
    this.image,
    this.type,
    this.emailVerifiedAt,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  EditProfileModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    udi = json['udi']?.toString();
    email = json['email']?.toString();
    mobileNumber = json['mobile_number']?.toString();
    phoneNumber = json['phone_number']?.toString();
    deviceKey = json['device_key']?.toString();
    image = json['image']?.toString();
    type = json['type']?.toString();
    emailVerifiedAt = json['email_verified_at']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['udi'] = udi;
    data['email'] = email;
    data['mobile_number'] = mobileNumber;
    data['phone_number'] = phoneNumber;
    data['device_key'] = deviceKey;
    data['image'] = image;
    data['type'] = type;
    data['email_verified_at'] = emailVerifiedAt;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class EditProfileModel {
/*
{
  "success": true,
  "data": {
    "id": 37,
    "name": "khjkj",
    "udi": "25497610",
    "email": null,
    "mobile_number": "9673423411",
    "phone_number": null,
    "device_key": null,
    "image": "admin/home/profile/4386Group 34169.png",
    "type": "customer",
    "email_verified_at": null,
    "status": true,
    "created_at": "2024-05-24T05:12:28.000000Z",
    "updated_at": "2024-05-24T05:33:54.000000Z",
    "deleted_at": null
  },
  "message": "Profile Edit Successfully."
} 
*/

  bool? success;
  EditProfileModelData? data;
  String? message;

  EditProfileModel({
    this.success,
    this.data,
    this.message,
  });
  EditProfileModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? EditProfileModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
