///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DepositAmountModelData {
/*
{
  "id": 1,
  "channel_id": 1,
  "value": "1000",
  "amount": "1k",
  "status": true,
  "created_at": "2024-05-02T07:45:21.000000Z",
  "updated_at": "2024-05-02T07:45:21.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  int? channelId;
  String? value;
  String? amount;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  DepositAmountModelData({
    this.id,
    this.channelId,
    this.value,
    this.amount,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  DepositAmountModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    channelId = json['channel_id']?.toInt();
    value = json['value']?.toString();
    amount = json['amount']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['channel_id'] = channelId;
    data['value'] = value;
    data['amount'] = amount;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class DepositAmountModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "channel_id": 1,
      "value": "1000",
      "amount": "1k",
      "status": true,
      "created_at": "2024-05-02T07:45:21.000000Z",
      "updated_at": "2024-05-02T07:45:21.000000Z",
      "deleted_at": null
    }
  ],
  "message": "Deposit Amount Get successfully."
} 
*/

  bool? success;
  List<DepositAmountModelData?>? data;
  String? message;

  DepositAmountModel({
    this.success,
    this.data,
    this.message,
  });
  DepositAmountModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <DepositAmountModelData>[];
      v.forEach((v) {
        arr0.add(DepositAmountModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
