///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DepositHistoryModelData {
/*
{
  "id": 1791,
  "user_id": 35,
  "wallet_id": 37,
  "transaction_type": "UPI",
  "transaction_number": null,
  "transaction_status": "Complete",
  "amount": "200.00",
  "type": "Deposite",
  "mobile_number": null,
  "bank_number": null,
  "name": null,
  "channel_id": 1,
  "deposit_amount_id": 2,
  "bet_id": null,
  "status": true,
  "created_at": "2024-05-28T12:49:38.000000Z",
  "updated_at": "2024-05-28T12:49:38.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  int? userId;
  int? walletId;
  String? transactionType;
  String? transactionNumber;
  String? transactionStatus;
  String? amount;
  String? type;
  String? mobileNumber;
  String? bankNumber;
  String? name;
  int? channelId;
  int? depositAmountId;
  String? betId;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  DepositHistoryModelData({
    this.id,
    this.userId,
    this.walletId,
    this.transactionType,
    this.transactionNumber,
    this.transactionStatus,
    this.amount,
    this.type,
    this.mobileNumber,
    this.bankNumber,
    this.name,
    this.channelId,
    this.depositAmountId,
    this.betId,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  DepositHistoryModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['user_id']?.toInt();
    walletId = json['wallet_id']?.toInt();
    transactionType = json['transaction_type']?.toString();
    transactionNumber = json['transaction_number']?.toString();
    transactionStatus = json['transaction_status']?.toString();
    amount = json['amount']?.toString();
    type = json['type']?.toString();
    mobileNumber = json['mobile_number']?.toString();
    bankNumber = json['bank_number']?.toString();
    name = json['name']?.toString();
    channelId = json['channel_id']?.toInt();
    depositAmountId = json['deposit_amount_id']?.toInt();
    betId = json['bet_id']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['wallet_id'] = walletId;
    data['transaction_type'] = transactionType;
    data['transaction_number'] = transactionNumber;
    data['transaction_status'] = transactionStatus;
    data['amount'] = amount;
    data['type'] = type;
    data['mobile_number'] = mobileNumber;
    data['bank_number'] = bankNumber;
    data['name'] = name;
    data['channel_id'] = channelId;
    data['deposit_amount_id'] = depositAmountId;
    data['bet_id'] = betId;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class DepositHistoryModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1791,
      "user_id": 35,
      "wallet_id": 37,
      "transaction_type": "UPI",
      "transaction_number": null,
      "transaction_status": "Complete",
      "amount": "200.00",
      "type": "Deposite",
      "mobile_number": null,
      "bank_number": null,
      "name": null,
      "channel_id": 1,
      "deposit_amount_id": 2,
      "bet_id": null,
      "status": true,
      "created_at": "2024-05-28T12:49:38.000000Z",
      "updated_at": "2024-05-28T12:49:38.000000Z",
      "deleted_at": null
    }
  ],
  "message": "Deposite History Get successfully."
} 
*/

  bool? success;
  List<DepositHistoryModelData?>? data;
  String? message;

  DepositHistoryModel({
    this.success,
    this.data,
    this.message,
  });
  DepositHistoryModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <DepositHistoryModelData>[];
      v.forEach((v) {
        arr0.add(DepositHistoryModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
