///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChannelModelData {
/*
{
  "id": 1,
  "name": "7 Days Pay- app",
  "balance": "100-1000k",
  "days": "7",
  "status": true,
  "created_at": "2024-05-02T07:26:50.000000Z",
  "updated_at": "2024-05-02T07:27:04.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  String? name;
  String? balance;
  String? days;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  ChannelModelData({
    this.id,
    this.name,
    this.balance,
    this.days,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  ChannelModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    balance = json['balance']?.toString();
    days = json['days']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['balance'] = balance;
    data['days'] = days;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class ChannelModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 1,
      "name": "7 Days Pay- app",
      "balance": "100-1000k",
      "days": "7",
      "status": true,
      "created_at": "2024-05-02T07:26:50.000000Z",
      "updated_at": "2024-05-02T07:27:04.000000Z",
      "deleted_at": null
    }
  ],
  "message": "Channel Get successfully."
} 
*/

  bool? success;
  List<ChannelModelData?>? data;
  String? message;

  ChannelModel({
    this.success,
    this.data,
    this.message,
  });
  ChannelModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ChannelModelData>[];
  v.forEach((v) {
  arr0.add(ChannelModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
