///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SendDepositModelData {
/*
{
  "user_id": 35,
  "wallet_id": 37,
  "transaction_type": "UPI",
  "transaction_number": null,
  "transaction_status": "Complete",
  "amount": "100",
  "type": "Deposite",
  "channel_id": "1",
  "deposit_amount_id": "5",
  "status": true,
  "updated_at": "2024-05-28T12:55:38.000000Z",
  "created_at": "2024-05-28T12:55:38.000000Z",
  "id": 1796
} 
*/

  int? userId;
  int? walletId;
  String? transactionType;
  String? transactionNumber;
  String? transactionStatus;
  String? amount;
  String? type;
  String? channelId;
  String? depositAmountId;
  bool? status;
  String? updatedAt;
  String? createdAt;
  int? id;

  SendDepositModelData({
    this.userId,
    this.walletId,
    this.transactionType,
    this.transactionNumber,
    this.transactionStatus,
    this.amount,
    this.type,
    this.channelId,
    this.depositAmountId,
    this.status,
    this.updatedAt,
    this.createdAt,
    this.id,
  });
  SendDepositModelData.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toInt();
    walletId = json['wallet_id']?.toInt();
    transactionType = json['transaction_type']?.toString();
    transactionNumber = json['transaction_number']?.toString();
    transactionStatus = json['transaction_status']?.toString();
    amount = json['amount']?.toString();
    type = json['type']?.toString();
    channelId = json['channel_id']?.toString();
    depositAmountId = json['deposit_amount_id']?.toString();
    status = json['status'];
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['wallet_id'] = walletId;
    data['transaction_type'] = transactionType;
    data['transaction_number'] = transactionNumber;
    data['transaction_status'] = transactionStatus;
    data['amount'] = amount;
    data['type'] = type;
    data['channel_id'] = channelId;
    data['deposit_amount_id'] = depositAmountId;
    data['status'] = status;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    return data;
  }
}

class SendDepositModel {
/*
{
  "success": true,
  "data": {
    "user_id": 35,
    "wallet_id": 37,
    "transaction_type": "UPI",
    "transaction_number": null,
    "transaction_status": "Complete",
    "amount": "100",
    "type": "Deposite",
    "channel_id": "1",
    "deposit_amount_id": "5",
    "status": true,
    "updated_at": "2024-05-28T12:55:38.000000Z",
    "created_at": "2024-05-28T12:55:38.000000Z",
    "id": 1796
  },
  "message": "Deposite added successfully."
} 
*/

  bool? success;
  SendDepositModelData? data;
  String? message;

  SendDepositModel({
    this.success,
    this.data,
    this.message,
  });
  SendDepositModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? SendDepositModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
