///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WithdrawHistoryModelData {
/*
{
  "transaction_type": "UPI",
  "transaction_number": "upi98741651564",
  "transaction_status": "Completed",
  "amount": "5000.00",
  "type": "Deposite",
  "created_at": "2024-05-02T11:01:26.000000Z"
} 
*/

  String? transactionType;
  String? transactionNumber;
  String? transactionStatus;
  String? amount;
  String? type;
  String? createdAt;

  WithdrawHistoryModelData({
    this.transactionType,
    this.transactionNumber,
    this.transactionStatus,
    this.amount,
    this.type,
    this.createdAt,
  });
  WithdrawHistoryModelData.fromJson(Map<String, dynamic> json) {
    transactionType = json['transaction_type']?.toString();
    transactionNumber = json['transaction_number']?.toString();
    transactionStatus = json['transaction_status']?.toString();
    amount = json['amount']?.toString();
    type = json['type']?.toString();
    createdAt = json['created_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['transaction_type'] = transactionType;
    data['transaction_number'] = transactionNumber;
    data['transaction_status'] = transactionStatus;
    data['amount'] = amount;
    data['type'] = type;
    data['created_at'] = createdAt;
    return data;
  }
}

class WithdrawHistoryModel {
/*
{
  "success": true,
  "data": [
    {
      "transaction_type": "UPI",
      "transaction_number": "upi98741651564",
      "transaction_status": "Completed",
      "amount": "5000.00",
      "type": "Deposite",
      "created_at": "2024-05-02T11:01:26.000000Z"
    }
  ],
  "message": "Deposite History Get successfully."
} 
*/

  bool? success;
  List<WithdrawHistoryModelData?>? data;
  String? message;

  WithdrawHistoryModel({
    this.success,
    this.data,
    this.message,
  });
  WithdrawHistoryModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WithdrawHistoryModelData>[];
      v.forEach((v) {
        arr0.add(WithdrawHistoryModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
