///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CustomerServiceModelData {
/*
{
  "id": 1,
  "name": "First",
  "number": "9549874561",
  "image": "public/admin/customerService/99LOGO (1).jpg",
  "status": true,
  "created_at": "2024-05-03T14:16:14.000000Z",
  "updated_at": "2024-05-16T13:16:03.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  String? name;
  String? number;
  String? image;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  CustomerServiceModelData({
    this.id,
    this.name,
    this.number,
    this.image,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  CustomerServiceModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    number = json['number']?.toString();
    image = json['image']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }

  bool? get isNotEmpty => null;
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['number'] = number;
    data['image'] = image;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class CustomerServiceModel {
/*
{
  "success": true,
  "data": {
    "id": 1,
    "name": "First",
    "number": "9549874561",
    "image": "public/admin/customerService/99LOGO (1).jpg",
    "status": true,
    "created_at": "2024-05-03T14:16:14.000000Z",
    "updated_at": "2024-05-16T13:16:03.000000Z",
    "deleted_at": null
  },
  "message": "customer Service get successfully."
} 
*/

  bool? success;
  CustomerServiceModelData? data;
  String? message;

  CustomerServiceModel({
    this.success,
    this.data,
    this.message,
  });
  CustomerServiceModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? CustomerServiceModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
