///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AttendenceBonusModelData {
/*
{
  "id": 7,
  "amount": "100",
  "bonus": "10",
  "days": "1",
  "status": true,
  "created_at": "2024-05-30T10:02:36.000000Z",
  "updated_at": "2024-05-30T10:02:36.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  String? amount;
  String? bonus;
  String? days;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  AttendenceBonusModelData({
    this.id,
    this.amount,
    this.bonus,
    this.days,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  AttendenceBonusModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    amount = json['amount']?.toString();
    bonus = json['bonus']?.toString();
    days = json['days']?.toString();
    status = json['status'];
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['amount'] = amount;
    data['bonus'] = bonus;
    data['days'] = days;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class AttendenceBonusModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 7,
      "amount": "100",
      "bonus": "10",
      "days": "1",
      "status": true,
      "created_at": "2024-05-30T10:02:36.000000Z",
      "updated_at": "2024-05-30T10:02:36.000000Z",
      "deleted_at": null
    }
  ],
  "message": "Attendence Bonus Get successfully."
} 
*/

  bool? success;
  List<AttendenceBonusModelData?>? data;
  String? message;

  AttendenceBonusModel({
    this.success,
    this.data,
    this.message,
  });
  AttendenceBonusModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AttendenceBonusModelData>[];
      v.forEach((v) {
        arr0.add(AttendenceBonusModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
